### ISSUE TITLE
installing img

### ISSUE THREAD

**Issue by unupingu** [Telegea/Smarthub-software#2]
Hy 
i"m tryng to install img using partprobe but after finishing there is nothing on my lcd .something is booting on my raspberry but i"stuck with a white screen.
if you can help me because im not good at programing.

thanks

**Comment by ondrej1024** [comment]
What Raspberry Pi version are you using? The SD card image is probably not running on the RPi3. This has not been tested yet. It works fine on the original RPi and RPi2

**Comment by unupingu** [comment]
I'm using RPi 3

**Comment by ondrej1024** [comment]
Then I think it's time we should support RPi3 too. I will look into that. The next image will most likely support it.

**Comment by unupingu** [comment]
Ok thank.

**Comment by unupingu** [comment]
Hi,
How about RPi zero?

**Comment by ondrej1024** [comment]
We haven't tried that yet. But the RPi Zero has the same Broadcom chip BCM2835 which is used on RPi1 and Compute Module1 which run the SmartHub OS just fine. So in theory it _should_ work.

**Comment by unupingu** [comment]
I think is not working because when I boot I get an white screen.Or I have done something rong

**Comment by ondrej1024** [comment]
Then I guess you have not created the SD card correctly. Can you copy the console message from the  createsd.sh script here?

**Comment by unupingu** [comment]
I think I can't because I did it a month a go and I don't remember how to do it again 


Inviato da Samsung Mobile.

<div>-------- Messaggio originale --------</div><div>Da: Ondrej Wisniewski <notifications@github.com> </div><div>Data:22/06/2017  18:53  (GMT+01:00) </div><div>A: Telegea/Smarthub-software <Smarthub-software@noreply.github.com> </div><div>Cc: unupingu <pingu_gabry83@libero.it>, Author <author@noreply.github.com> </div><div>Oggetto: Re: [Telegea/Smarthub-software] installing img (#2) </div><div>
</div>Then I guess you have not created the SD card correctly. Can you copy the console message from the createsd.sh script here?

**Comment by unupingu** [comment]
I will try to do it again.


Inviato da Samsung Mobile.

<div>-------- Messaggio originale --------</div><div>Da: Ondrej Wisniewski <notifications@github.com> </div><div>Data:22/06/2017  18:53  (GMT+01:00) </div><div>A: Telegea/Smarthub-software <Smarthub-software@noreply.github.com> </div><div>Cc: unupingu <pingu_gabry83@libero.it>, Author <author@noreply.github.com> </div><div>Oggetto: Re: [Telegea/Smarthub-software] installing img (#2) </div><div>
</div>Then I guess you have not created the SD card correctly. Can you copy the console message from the createsd.sh script here?

**Comment by unupingu** [comment]
I have a screenshot with the console message, how can I send you the file?

**Comment by ondrej1024** [comment]
You can attach files here (just drag and drop).

**Comment by unupingu** [comment]
Inviato da Samsung Mobile.

<div>-------- Messaggio originale --------</div><div>Da: Ondrej Wisniewski <notifications@github.com> </div><div>Data:23/06/2017  08:31  (GMT+01:00) </div><div>A: Telegea/Smarthub-software <Smarthub-software@noreply.github.com> </div><div>Cc: unupingu <pingu_gabry83@libero.it>, Author <author@noreply.github.com> </div><div>Oggetto: Re: [Telegea/Smarthub-software] installing img (#2) </div><div>
</div>You can attach files here (just drag and drop).

**Comment by unupingu** [comment]
I have tried one more time


Inviato da Samsung Mobile.

<div>-------- Messaggio originale --------</div><div>Da: Ondrej Wisniewski <notifications@github.com> </div><div>Data:23/06/2017  08:31  (GMT+01:00) </div><div>A: Telegea/Smarthub-software <Smarthub-software@noreply.github.com> </div><div>Cc: unupingu <pingu_gabry83@libero.it>, Author <author@noreply.github.com> </div><div>Oggetto: Re: [Telegea/Smarthub-software] installing img (#2) </div><div>
</div>You can attach files here (just drag and drop).

**Comment by ondrej1024** [comment]
![image](https://user-images.githubusercontent.com/5494041/27488335-06043854-5837-11e7-92e1-7bc86615a0df.png)
Pasting a picture here works fine for me. Can't really help you with that.

**Comment by unupingu** [comment]
![smarthubosv3 1](https://user-images.githubusercontent.com/24717851/27495694-523bb1cc-5853-11e7-855a-19947c58bfa0.jpg)

**Comment by unupingu** [comment]
I think that is something rong with the file created. sh.on this line:
PART1_FILE=$IMGNAME-p1/*

**Comment by unupingu** [comment]
More exactly is that this "/*" has to be deleted

**Comment by ondrej1024** [comment]
Sorry for keeping you waiting. Just now I had a chance to look at the screenshot. 

There are error messages so the SD card was not created correctly. The script works fine, though. I have created o lot of SD cards with it. But you have to make sure that the image file is in the same directory where you call the script from. So you should launch the script like this (if your SD card is at /dev/sdb):
`sudo ./createsd.sh smarthubosV3.1.tgz /dev/sdb`

If you still get errors please download the latest image smarthubosV3.2.tgz and try with this one.

The script is not perfect and should do some more error checking but if you call it as described above it works fine.

**Comment by ondrej1024** [comment]
I just tested again. The smarthubosV3.1.tgz works perfectly. Version 3.2 is not yet released (sorry for the confusion). And it boots also on an RPi 3. Can't test RPi Zero because I don't have it here.

**Comment by unupingu** [comment]
i did sudo ./ createsd.sh smarthubosV3.1.tgz /dev/mmcblk0

**Comment by unupingu** [comment]
on raspberry pi3 and zero

**Comment by ondrej1024** [comment]
Are you saying you create the SD card on your RPi? 
Writing the image to `/dev/mmcblk0` will erase the SD card you have booted from (and where you stored the image itself, I guess). Or am I missing something?

**Comment by unupingu** [comment]
I am trying again at this moment but I think is not working

**Comment by unupingu** [comment]
My sd card is on dev/mmcblk0.
After the hole process with createsd.sh I get 3 partition mmcblk01 fat 16 ,mmcblk0p2 ext4 and mmcblk0p3 ext4

**Comment by unupingu** [comment]
I am using live linux cd gparted

**Comment by ondrej1024** [comment]
Just to understand this: you create the SD card on a PC which was booted from the live CD?

**Comment by unupingu** [comment]
Yes

**Comment by ondrej1024** [comment]
Please run the following command directly after the script has finished:
`ls -R | grep /`
I would like to see the directories which were created by the script.

**Comment by unupingu** [comment]
I want it to do the thermostat thing but if you don't  have the time to help me I'll give up.

**Comment by unupingu** [comment]
I get
./smarthubosV3.1:
./smarthubosV3.1/smarthubosV3.1:
./smarthubos.3.1/smarthubos.3.1/smarthubos.3.1-p1 
./smarthubosV3.1/smarthubos.3.1/smarthubosV3.1-p1/overlays

**Comment by ondrej1024** [comment]
I think I know what's going on. There was an old version of the createsd.sh script here on Github. I just updated it.
So please get the latest version and try again, now it should work. Thanks for your patience :sweat_smile:

**Comment by unupingu** [comment]
It worked without errors
But when I boot on raspberry I get a white screen
Raspberry is boot in corectly by watching the green led

**Comment by ondrej1024** [comment]
There should be the boot messages on the screen and the login prompt eventually. But you don't really need the screen. If you connect the network cable to the RPi then the green led will start flashing regularly (1Hz) at the end of the boot process. This means you can connect to the RPi via ssh where you can do the configuration.

**Comment by unupingu** [comment]
I am using a 3.5 tft display.if I conect a hdmi to the raspberry and then plug on to tv I get a message boot the it stops on something like fbtft of value fs=25.what is the username and password.

**Comment by ondrej1024** [comment]
There is only the root account. Default root password is `sm@rthub`
You can find this and other useful information on the [release page](https://github.com/Telegea/Smarthub-software/releases/tag/V3.1)

**Comment by unupingu** [comment]
For using the tft I have to reinstall my driver that It I bought along with the display?

**Comment by unupingu** [comment]
Im in.
Now I have to figer it out how to use ini syntax to configure the thermostat thing

**Comment by ondrej1024** [comment]
The Smart Hub is a headless system which is managed remotely via network connection. This can be done without local display.

Do you need the display for the thermostat GUI?  We support the Adafruit resistive and capacitive TFT Displays. To enable this you have to uncomment one of the two lines in `/boot/config.txt`:

```
############################################
# Enable this if resistive touchscreen is used
############################################
#dtoverlay=pitft28-resistive,speed=32000000,rotate=270

############################################
# Enable this if capacitive touchscreen is used
############################################
#dtoverlay=pitft28-capacitive,speed=32000000,rotate=270,invy=1,swapxy=1
```
You should also comment these lines:
```
############################################
# SPI is used for DHT sensor on connector 1
# Note: disable this if touchscreen is used
############################################
dtparam=spi=on
dtoverlay=spi-gpio35-39
```
Just read through the comments in this file and adjust the parameters as needed by your system. Currently the settings are specific for the [Telegea Smart Hub](https://www.telegea.org/smart-hub/) custom hardware so some things need to be changed for the RPi.

**Comment by unupingu** [comment]
Thank a lot for your help.if your kindly I need a last thing that is how to enable thermostat with telegea.conf. what sintax I have to put in the shell to enable .thanks again

**Comment by ondrej1024** [comment]
Before doing the configuration I need to know what your hardware setup is. What temperature sensor and relay card do you have?

**Comment by unupingu** [comment]
Sensor ds18b20  and a SSR

**Comment by unupingu** [comment]
Or a normal relay

**Comment by ondrej1024** [comment]
The configuration is done in the file `/etc/telegea.conf`

First you have to configure the temperature sensor. Go to the `[sensord]` section and change the pin number to the one used by your 1-wire bus:

```
# GPIO line used by 1w-therm driver
W1_THERM_PIN=13
```
Then add the code of your specific sensor to the list of sensors:
 ```
# 1-wire sensor codes (leave empty if not used)
W1_SENSOR1=28-XXXXXXXXXXXX ; add you sensor code here
W1_SENSOR2=
W1_SENSOR3=
```
You can find the code of your sensor by running this command
`ls -l /sys/bus/w1/devices`

**Comment by ondrej1024** [comment]
Then you need to configure the relay in the `[controld]` section.

```
# List of Ids of the GPIO pins we want to control
# and associated control files
# External relay cards connected via I2C GPIO expander
# chip are addressed like local GPIO pins
# Set to "0" if unused
GPIO1_ID=XX               ; add GPIO pin connected to your relay here
GPIO1_CONTROL_FILE="/media/data/control9"
GPIO2_ID=0               ; set all other pins to 0
GPIO2_CONTROL_FILE="/media/data/control10"
GPIO3_ID=0               ; set all other pins to 0
```

**Comment by ondrej1024** [comment]
Now you can modify the `[thermostat]` section as follows:

```
##################################################################################
# Parameters for thermostat module
##################################################################################

THERMOSTAT_ENABLED=true

MAX_TEMP=40
MIN_TEMP=10
MAX_OPERATING_TIME=120 ;minutes
MIN_IDLE_TIME=5        ;minutes
ROOM_TEMP_REG_NAME="Temperature 1 "
HEATCOOL_CTRL1_REG_NAME="Control 1 "
HEATCOOL_CTRL2_REG_NAME=
SEASON_MODE="heating"  ;heating or cooling
USER_MODE="smart"      ;smart or dumb
TEMP_OFFSET=0

```

**Comment by ondrej1024** [comment]
As last step you need to enable the touch screen GUI in the `[thermostatgui]` section
```
[thermostatgui]
##################################################################################
# Parameters for thermostat GUI
##################################################################################

THERMOSTATGUI_ENABLED=true

THERMOSTAT_DEVICE_IP="127.0.0.1"

# Geografic location (city,country)
LOCATION=

# Open Weather Map data
OWM_API="http://api.openweathermap.org/data/2.5/weather"
OWM_APPID=
```
If you want the weather info on the screen you need to add your location and get an APPID on openweathermap.org and add it to the configuration.

When all is done just do a reboot.

**Comment by ondrej1024** [comment]
I forgot that you have to change the 1-wire bus pin number also in `/boot/config.txt`

`dtoverlay=w1-gpio,gpiopin=4`

**Comment by unupingu** [comment]
About the lcd I hame to buy an Adafruit 2.8 tft or can I modify something to work with my 3.5 tft from sunfounder.com

**Comment by unupingu** [comment]
i have managed to make it work by adding 
dtparam=spi=on
dtparam=i2c_arm=on
dtoverlay=piscreen,debug=3
but my y axes is inverted i have to touch the bottom of the screen to icrease temp

**Comment by ondrej1024** [comment]
You can check the script `/usr/local/bin/thermostat-gui.sh` which has these lines to invert the touch screen axis:
```
# Swap x and y axis (needed if screen is rotated 90° or 270°)
DISPLAY=:0 xinput --set-prop 'ADS7846 Touchscreen' 'Evdev Axes Swap' 1
#DISPLAY=:0 xinput --set-prop 'stmpe-ts' 'Evdev Axes Swap' 1
# Invert Y axis on touchscreen (needed if screen is rotated 270°)
DISPLAY=:0 xinput --set-prop 'ADS7846 Touchscreen' 'Evdev Axis Inversion' 0 1
#DISPLAY=:0 xinput --set-prop 'stmpe-ts' 'Evdev Axis Inversion' 0 1
```
This has worked here for the Watterott 2.8'' touch display. For your display the string for the `--set-prop` parameter is probably different.

**Comment by unupingu** [comment]
I can't modify the file because is readonly

**Comment by ondrej1024** [comment]
The whole root partition is readonly. You have to remount it in read/write mode. Use the `rmnt` command (alias) to do this.
You can do **anything** on the Smart Hub, you are root. :smile:

**Comment by unupingu** [comment]
It worked.
I have entered the api key to telegea.conf for openweathermap.org but is not showing the weather on display.
Thanks again

**Comment by unupingu** [comment]
I think the plant is DEMO.but the api key?

**Comment by ondrej1024** [comment]
Your SmartHub (RPi) has to be registered with your account on the telegea server. Unfortunately there is no automatic procedure yet to do that (we still need to implement it). So we will do the registration manually on Monday. Then you will get your plant_id and api_key by e-mail.

**Comment by unupingu** [comment]
Ok thank a lot

**Comment by unupingu** [comment]
Thanks for the id and api.
I have to insert them in telegea.conf  with quotes  " or without? 
And another thing is that on the screen I don't have the state of the thermostat  ( on of winter summer. ...)

**Comment by ondrej1024** [comment]
plant id and api key go into the conf file without quotes (actually I think it makes no difference)

For the screen issue, can you show a screenshot of the display and the `[thermostat]` section of your telegea.conf ?

**Comment by unupingu** [comment]
[Document1.docx](https://github.com/Telegea/Smarthub-software/files/1120073/Document1.docx)
![screen rpi](https://user-images.githubusercontent.com/24717851/27800599-687dd27a-601a-11e7-88b2-e1c16f559e08.jpg)

**Comment by unupingu** [comment]
[telegea.conf.docx](https://github.com/Telegea/Smarthub-software/files/1120087/telegea.conf.docx)

**Comment by ondrej1024** [comment]
The thermostat application is not running on your RPi because you didn't configure it correctly. You should follow precisely the instructions I posted before. 
In particular you need to configure the temperature sensor and the relay control as shown in the previous posts otherwise the application will not be able to run.

**Comment by ondrej1024** [comment]
The configuration of the thermostat is not so straight forward at the moment. Unfortunately we have not worked very much on improving this lately because we were busy implementing a completely new thermostat application from scratch. This new thermostat has many advanced features that the old one doesn't have like multiple zone support, smartphone app and a new touchscreen interface. Right now the touchscreen interface runs on the 7'' RPi display only and we haven't implemented yet the support for small local screens like yours.

But within the next few weeks we want to release a new SD card image which has the new thermostat application pre-configured and it should be much easier to set this up, even for beginnners.

This is what the new display looks like:

![image](https://user-images.githubusercontent.com/5494041/27820647-bae415c6-609f-11e7-9271-b85eae984202.png)

**Comment by unupingu** [comment]
Cooool! !!!!!!!!!!!.

**Comment by unupingu** [comment]
I've seen a lot of projects with thermostat but I never seen a project that has schedule control ed from the touch screen and why not a web radio included too.what do you think about that?

**Comment by ondrej1024** [comment]
We already have the schedule page on the 7'' touch screen. But it is probably not possible to put this on a small 3.5'' display.

![image](https://user-images.githubusercontent.com/5494041/27829948-6a244af0-60c4-11e7-9295-af30d1914ecf.png)

**Comment by unupingu** [comment]
![thermostat_touch](https://user-images.githubusercontent.com/24717851/27842263-aa5ea5ea-6108-11e7-8c38-be026af9e15e.jpg)
I've made one like this with 7 inch tft.

**Comment by ondrej1024** [comment]
What software are you using for this?

**Comment by unupingu** [comment]
Kivy 1.9.1

**Comment by unupingu** [comment]
hi again.
i have been tryng again and again to make the thermostat to function but it is not working .
on my telegea.org i get the temperature but the display says 0.0 and the status of the thermostat is not diplaying.i made the modification that you told me.
i hope you can help me

**Comment by unupingu** [comment]
hi again .
i did that you told me to do to enable the thermostat but all i get is 
[Document2.docx](https://github.com/Telegea/Smarthub-software/files/1156195/Document2.docx)
on my.telegea.org i get the temp 1 
[my.telegea.file.docx](https://github.com/Telegea/Smarthub-software/files/1156199/my.telegea.file.docx)
any ideeas?

**Comment by unupingu** [comment]
this is my telegea.conf.
[telegea.conf.docx](https://github.com/Telegea/Smarthub-software/files/1156262/telegea.conf.docx)

**Comment by ondrej1024** [comment]
I connected to your smarthub and fixed some issues in the configuration. The thermostat should work now.

**Comment by ondrej1024** [comment]
As I said before, the development of the Smart Hub software has been progressing but we have not updated the thermostat code for a long time because it will be completely replaced by the new thcontrol module. There are some issues at the moment with the thermostat module.  You should not run both modules together unless you know what you are doing, it will cause trouble.
The next release of the SD card image will have the thcontrol module configured with good default values and it should work "out of the box" without complicated setup.

It is vacation time here at the moment and I will not be able to support you until the beginning of august. Hope you will manage.

**Comment by ondrej1024** [comment]
Remember that you should not post the complete configuration file (including your API key here), someone could use it  to access your data.
Disable the sshtunnel module if you don't want me to connect to your smart hub remotely.

**Comment by unupingu** [comment]
Ok thanks a lot

**Comment by unupingu** [comment]
When I plug it off and then plug it on again the temp it says 0.0 set temp 0.0 like the first time

**Comment by ondrej1024** [comment]
Sorry for keep you waiting but I've just come back from vacation. Did you manage to solve this issue in the meantime?
If not I can try to connect to your SmartHub and see what's happening.

**Comment by unupingu** [comment]
hy.
and welcome back.
no i didnt solved yet.
try to connect to it
thanks

**Comment by ondrej1024** [comment]
ok, I will have a look this morning, leave the SmartHub switched on and connected please.

**Comment by unupingu** [comment]
Ok .now is working.
What was it?

**Comment by unupingu** [comment]
What I have to change to get the set temp scale to increase or decrease to 0.2 decrease instead of 1 degrease?
And how  to access the scheduled ?
Thanks again

**Comment by unupingu** [comment]
What I have to change to get the set temp scale to increase or decrease to 0.2 degrease instead of 1 degrease?
And how  to access the scheduled ?
Thanks again

**Comment by ondrej1024** [comment]
As I said before, the thermostat application has not been maintained for a long time and it doesn't work well together with the rest of the system. There was an issue with the schedule file that doesn't actually contain a schedule, so the "smart" mode is not working. I changed the thermostat mode to "dumb". It would take a long time to explain exactly what this means and all the details. It's not really worth it because this application will be completely replaced by the new thcontrol application. I am working on making the thermostat-gui compatible with thcontrol and will release a new SD card image with a system which should work "out of the box". Then also the schedule configuration GUI on the web interface and the smartphone app will work, which is not possible with the old thermostat application. So please be patient.

**Comment by unupingu** [comment]
ok i will close the issues .
i really aprecieted yor help.

**Comment by ondrej1024** [comment]
In order to change the step size for increasing/decreasing the target temperature, you need to modify the  JavaScript function `modifyTemp()` in `/var/www/therm/index.php`
