### ISSUE TITLE
Connections refused with Raspbian Stretch

### ISSUE THREAD

**Issue by Brshk1** [Telegea/Smarthub-software#6]
Hi,

I am trying to install Telegea Smarthub sw from scratch and on the latest Raspbian version. I have been delayed by being unable to reconnect to the RPi3 after copying fsmods/etc/*. As the title reads, all connections are refused. I have tracked the problem down to the line with /var/lock in /etc/fstab:
tmpfs           /var/lock       tmpfs   defaults,noatime 0 0

Without it, all works all right. It seems that /var/lock is symlinked to /run/lock and /run is already a tmpfs.

There are as well some prerequisites that need to be installed, such as automake and libtools and others that I cannot remember.

Anyway, thanks for the project. It will cover perfectly my needs.

**Comment by ondrej1024** [comment]
Probably the [installation guide](https://github.com/Telegea/Smarthub-software/blob/master/doc/raspi-os-installation.md) needs to be modified for installation on latest Raspbian distros. The guide uses Minibian as starting point for the installation so I guess there will be some differences.
If you managed to go through the installation process, it would be good if you could write a guide specifically for Raspbian, based on your experience. Would be greatly appreciated. Thanks.

**Comment by Brshk1** [comment]
I might as well. I knew my plan was a little bit like walking on the knife's edge, but, security-wise, it is better to rely on an updated OS these days.

You can close the issue if you want, by the way.
